config/routes.rb
Rails.application.routes.draw do

  root 'bogs#index'

    resources :creatures
    get 'creatures/tag/:tag' => 'creatures#tag', as: :tag
    get 'creatures/tags' => 'creatures#tags'
    get 'tags' => 'tags#index'

    get '*path', to: "application#not_found"

end

app/models/bogs.rb
class Bogs < ActiveRecord::Base
end

app/models/creature.rb
class Creature < ActiveRecord::Base
    # validates :name, :uniqueness => {:case_sensitive => false}

    has_and_belongs_to_many :tags

    validates :name, presence: true, :uniqueness => {:case_sensitive => false}, format: { with: /\A[a-z\sA-Z]+\z/,
    message: "only allows letters" }
    validates :desc, presence: true, length: { in: 10..255 }
end

app/models/creatures_tags.rb
class CreaturesTags < ActiveRecord::Base
  belongs_to :creature
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base

  has_and_belongs_to_many :creatures

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end

end

app/controllers/bogs_controller.rb
class BogsController < ApplicationController

  def index
    #render plain: "test"
    # ^ this is a way to test the index action, before you create an index.html.erb.
  end

end

app/controllers/creatures_controller.rb
class CreaturesController < ApplicationController
  before_action :locate_creature, only: [:show, :edit, :update]

  def index
    @creature_list = Creature.all
  end

  def new
    @creature = Creature.new
    @tags = Tag.all
  end

  def edit
    @creature = Creature.find(params[:id])
    @tags = Tag.all
  end

  def create
    # render json: params
    @creature = Creature.create(creatures_params)

    # if @creature.save
    #   flash[:success] = "Your creature has been added"
    #   @creature.tags.clear
    #   tags = params[:creature][:tag_ids]
    #   tags.each do |tag_id|
    #     @creature.tags << Tag.find(tag_id) unless tag_id.blank?
    #   end
    #   redirect_to creatures_path
    # else
    #   @tags = Tag.all
    #   render 'new'
    # end

    if @creature.save(creatures_params)
      @creature.tags.clear
      tags = params[:creature][:tag_ids].split(",")
      tags.each do |name|
        @creature.tags << Tag.find_or_create_by({name: name}) unless name.blank?
      end
      redirect_to creatures_path
    else
      render 'edit'
    end
  end

  def update
    @creature = Creature.find_by_id(params[:id])

    # if @creature.update(creatures_params)
    #   @creature.tags.clear
    #   tags = params[:creature][:tag_ids]
    #   tags.each do |tag_id|
    #     @creature.tags << Tag.find(tag_id) unless tag_id.blank?
    #   end
    #   redirect_to creatures_path
    # else
    #   render 'edit'
    # end

    if @creature.update(creatures_params)
      @creature.tags.clear
      tags = params[:creature][:tag_ids].split(",")
      tags.each do |name|
        @creature.tags << Tag.find_or_create_by({name: name}) unless name.blank?
      end
      redirect_to creatures_path
    else
      render 'edit'
    end

  end

  def show
    @creature = Creature.find_by_id(params[:id])

    list = flickr.photos.search :text => @creature.name, :sort => "relevance"

    @results = list.map do |photo|
      FlickRaw.url_s(photo)
    end
  end

  def destroy
    @creature = Creature.find(params[:id])
    @creature.destroy

    redirect_to creatures_path
  end

  def tag
    tag = Tag.find_by_name(params[:tag])
      @creatures = tag ? tag.creatures : []
  end

  # def tags
  #   @creatures = Creature.all

  #   @tags = Tag.select("tags.*,count(creatures.id) AS creature_count").joins(:creatures).group("tags.id").order("creature_count DESC").limit(15)
  # end

private

  def creatures_params
    params.require(:creature).permit(:name,:desc)
  end

  def locate_creature
    not_found unless @creature = Creature.find_by_id(params[:id])
      # redirect_to '/404.html'
    # end
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    # @tags = Tag.all
    @creatures = Creature.all

    @tags = Tag.select("tags.*,count(creatures.id) AS creature_count").joins(:creatures).group("tags.id").order("creature_count DESC").limit(15)

  end

  # def new
  #   @tag = Tag.new
  #   @tags = Tag.all
  # end

  # def edit
  #   @tag = Tag.find(params[:id])
  # end

  # def create

  #   if @tag = Tag.create(tags_params)
  #     redirect_to tags_path
  #   else
  #     render 'edit'
  #   end
  # end

  # def update
  #   @tag = Tag.find_by_id(params[:id])
  #   if @tag.update(tags_params)
  #     redirect_to tags_path
  #   else
  #     render 'edit'
  #   end
  # end

  # private

  # def tags_params
  #   params.require(:tag).permit(:name)
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bogs/index.html.erb
<div class="index-outer col-md-12 text-center">
  <h1>WELCOME TO THE BOG APP</h1>
  <p id="bog-p">register, review, and explore the creatures who live beneath</p>
  <h4><%= link_to "Get started", new_creature_path %></h4>
</div>

<!-- creatures_new_path -->

app/views/creatures/edit.html.erb
<div class="outer col-md-6 col-md-offset-3">
  <div class="col-md-12 text-center">
    <h1>Edit <%= @creature.name %></h1>
  </div>
  <div class="col-md-6 col-md-offset-3">

    <% if @creature.errors.any? %>
    <div id="error_explanation">
      <h4>
        <%= pluralize(@creature.errors.count, "error") %> prohibited
        this creature from being saved:
      </h4>
      <ul>
        <% @creature.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

      <%= bootstrap_form_for @creature do |f| %>
      <%= f.text_field :name, :placeholder => "Creature Name" %>
      <%= f.text_area :desc, :placeholder => "Description" %>

      <%= f.text_field :tag_ids, :value => @creature.tags.map{|t|t.name}.join(","), 'data-role'=>'tagsinput' %>
      <%= f.submit :class => "btn btn-default btn-new" %>
    <% end %>
  </div>
</div>

app/views/creatures/index.html.erb
<div class="index-outer col-md-12">
  <div class="col-md-10 col-md-offset-1">
    <h1>Creatures</h1>


    <table class="table">
      <tr>
        <th>Creature</th>
        <th>Description</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
      <% @creature_list.each do |c| %>
      <tr>
        <td><%= c.name %></td>
        <td><%= c.desc %></td>
        <td>
          <button class="btn btn-default btn-md">
            <%= link_to "Show", creature_path(c.id) %>
          </button>
        </td>
        <td>
          <button class="btn btn-default btn-md">
            <%= link_to 'Delete', creature_path(c), method: :delete, data: {:confirm => 'Are you sure?'} %>
          </button>
        </td>
        <td>
          <button class="btn btn-default btn-md">
            <%= link_to "Edit", edit_creature_path(c) %>
          </button>
        </td>
      </tr>
      <%end%>
    </table>
  </div>
</div>

app/views/creatures/new.html.erb
<div class="outer col-md-6 col-md-offset-3">
  <div class="col-md-12 text-center">
    <h1>Register A New Creature</h1>
  </div>
  <div class="col-md-6 col-md-offset-3">

    <% if @creature.errors.any? %>
    <div id="error_explanation">
      <h4>
        <%= pluralize(@creature.errors.count, "error") %> prohibited
        this creature from being saved:
      </h4>
      <ul>
        <% @creature.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <%= bootstrap_form_for @creature do |f| %>
      <%= f.text_field :name, :placeholder => "Creature Name" %>
      <%= f.text_area :desc, :placeholder => "Description" %>

      <%= f.text_field :tag_ids, :placeholder => "Enter some tags!", :value => "", 'data-role'=>'tagsinput' %>
      <%= f.submit :class => "btn btn-default btn-new" %>
    <% end %>
  </div>
</div>

app/views/creatures/show.html.erb
<div class="outer col-md-6 col-md-offset-3">
  <div class="col-md-12 text-center">
    <h1 id="creature-desc"><%= @creature.name %></h1>
    <p id="creature-desc-p">Description: <%= @creature.desc %></p>
    <p id="tag-p">
      <b>Tags: </b>
      <% @creature.tags.each do |tag|%>
      <%= link_to tag.name, tag_path(tag.name) %>
      <% end %>
    </p>
  </div>
  <div class="col-md-12 text-center">
    <% @results[1..24].each do |photo| %>
    <a href="<%=photo.remove('_s')%>"><%= image_tag photo %></a>
    <% end %>
  </div>
</div>

app/views/creatures/tag.html.erb
<div class="index-outer col-md-12">
  <div class="col-md-10 col-md-offset-1">
    <h1>Tagged: "<%= params[:tag] %>"</h1>


    <table class="table">
      <tr>
        <th>Creature</th>
        <th>Description</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
      <% @creatures.each do |c| %>
      <tr>
        <td><%= c.name %></td>
        <td><%= c.desc %></td>
        <td>
          <button class="btn btn-default btn-md">
            <%= link_to "Show", creature_path(c.id) %>
          </button>
        </td>
        <td>
          <button class="btn btn-default btn-md">
            <%= link_to 'Delete', creature_path(c), method: :delete %>
          </button>
        </td>
        <td>
          <button class="btn btn-default btn-md">
            <%= link_to "Edit", edit_creature_path(c) %>
          </button>
        </td>
      </tr>
      <%end%>
    </table>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BogAppLab</title>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">
  <!-- <link href='http://fonts.googleapis.com/css?family=Exo' rel='stylesheet' type='text/css'> -->
  <link href='//fonts.googleapis.com/css?family=Julius+Sans+One' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand glyphicon glyphicon-home" href="/"></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!-- <li><a href="/">Home</a></li> -->
        <li><a href="/creatures">Creatures</a></li>
        <li><a href="/creatures/new">New Creature</a></li>
        <li><a href="/tags">Tags</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<%= render 'partials/flash' %>

<%= yield %>

</body>
</html>

app/views/partials/_flash.html.erb
<% if flash.any? %>
<% flash.each do |key, msg| %>
  <div class="alert alert-<%= key %>"><%= msg %></div>
  <% end %>
<% end %>

app/views/tags/edit.html.erb
<div class="outer col-md-6 col-md-offset-3">
  <div class="col-md-12 text-center">
    <h1>Edit: "<%= @tag.name %>"</h1>
  </div>
  <div class="col-md-6 col-md-offset-3">
    <%= bootstrap_form_for :tag do |f| %>
      <%= f.text_field :name, :placeholder => "Tag Name" %>
      <%= f.submit :class => "btn btn-default btn-new" %>
    <% end %>
  </div>
</div>

app/views/tags/index.html.erb
<div class="index-outer col-md-12">
  <div class="col-md-10 col-md-offset-1">
    <h1 align="center">Tags</h1>
    <p align="center">
    <% tag_max = @tags.map {|t| t.creatures.length}.sort.last %>
    <% @tags.each do |tag| %>
    <% fontsize = (tag.creatures.length.to_f / tag_max) * 30 %>
    <%= link_to tag.name, tag_path(tag.name), method: :get, :class => "tagcloud btn", :style => "font-size: #{fontsize.to_i + 5}px", :class => "btn btn-default padding" %>
    <% end %>
    </p>
  </div>
</div>

app/views/tags/new.html.erb
<div class="outer col-md-6 col-md-offset-3">
  <div class="col-md-12 text-center">
    <h1>Create a new tag</h1>
  </div>
  <div class="col-md-6 col-md-offset-3">
  <p id="tag-p">
    <b>Existing Tags: </b>
    <% @tags.each do |t| %>
      <%=t.name %>
    <% end %>
    </p>
    <%= bootstrap_form_for @tag do |f| %>
      <%= f.text_field :name, :placeholder => "Tag Name" %>
      <%= f.submit :class => "btn btn-default btn-new" %>
    <% end %>
  </div>
</div>